name: "PR validation"
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches-ignore:
      - staging
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.11
        run: sudo apt install python3.11
      - name: Install Pipenv
        run: pip install --user pipenv
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pipenv install --dev
      - name: Run migrations
        run: pipenv run python manage.py migrate
      - name: Run Tests
        run: pipenv run pytest
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: open5e-api:${{ github.ref_name }}
